config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, controller: 'sessions'

  ### Admin users
  constraints Passwordless::Constraint.new(User, if: -> (user) { user.admin }) do
    resources :links, only: [:edit, :update, :destroy] do
      get :unprocessed, to: 'links#unprocessed', on: :collection
    end
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :queued_links, only: [:index, :show, :destroy] do
      post :apply, to: 'queued_links#apply', on: :member
    end
  end

  ### Logged-in users
  constraints Passwordless::Constraint.new(User) do
    resources :links, only: [:new, :create] do
      get :import, to: 'links#import_new', on: :collection
      post :import, to: 'links#import_create', on: :collection
      post :import, to: 'links#run_import', on: :member
    end
    # combobox
    post "possibly_new_tag_chips", to: "tag_chips#create_possibly_new"
  end

  ### Anonymous users
  resources :tags, only: [:index, :show]
  resources :links, only: [:index, :show]
  get :advanced_search, to: 'home#advanced_search'
  get :advanced_search_results, to: 'home#advanced_search_results'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_query

  ALLOWED_SEARCH_FIELDS = ['title', 'notes', 'comment', 'text']

  def index
    if @query.present?
      @tags = Tag.where("name like ?", "%#{ActiveRecord::Base.sanitize_sql_like(@query)}%").order(:name)

      @links = Link.where("title like ?", "%#{ActiveRecord::Base.sanitize_sql_like(@query)}%")
        .or(Link.where("comment like ?", "%#{ActiveRecord::Base.sanitize_sql_like(@query)}%"))
        .or(Link.where("notes like ?", "%#{ActiveRecord::Base.sanitize_sql_like(@query)}%"))
        # Disabled for now, until the text is cleaned up.
        #.or(Link.where("text like ?", "%#{ActiveRecord::Base.sanitize_sql_like(@query)}%"))
        .or(Link.where(id: @tags.map {|t| t.links}.flatten.map { |l| l.id }.uniq))
    end

    if turbo_frame_request?
      render partial: "dynamic_homepage", locals: { links: @links, tags: @tags, query: @query }
    else
      render "index"
    end
  end

  def advanced_search
  end

  def advanced_search_results
    # Tokenize query.
    query = SearchTokenizer.tokenize(params[:query])

    # Restrict search_in to allowed fields.
    search_in = ALLOWED_SEARCH_FIELDS.intersection(params[:search_in])

    # Construct tag queries.
    @and_tags = Tag.where(id: params[:and_tags].split(','))
    @or_tags = Tag.where(id: params[:or_tags].split(','))
    @not_tags = Tag.where(id: params[:not_tags].split(','))

    and_tag_links = Link.where(id: @and_tags.map {|t| t.links.map {|l| l.id}}.reduce(&:intersection)&.uniq)
    or_tag_links = Link.where(id: @or_tags.map {|t| t.links}.flatten.map {|l| l.id}.uniq)
    not_tag_links = Link.where.not(id: @not_tags.map {|t| t.links}.flatten.map {|l| l.id}.uniq)

    # Do the actual field search.
    @links = Link.all
    if query.present? && search_in.present?
      @links = SearchConstructor.construct(Link, search_in, query)
    end

    # Then tie it all together.
    if @and_tags.present?
      @links = @links.and(and_tag_links)
    end

    if @or_tags.present?
      @links = @links.and(or_tag_links)
    end

    if @not_tags.present?
      @links = @links.and(not_tag_links)
    end
  end

private

  def set_query
    @query = params[:query]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dynamic_homepage.html.erb
<%= turbo_frame_tag "dynamic_homepage", target: "_top", refresh: "morph" do %>
  <% if @query.present? %>
    <%= render "search_results", links: @links, tags: @tags, query: @query %>
  <% else %>
    <turbo-stream action="update" target="page-title">
      <template><%= site_name %></template>
    </turbo-stream>
    <div id="selected_links">
      <h2>Latest links</h2>
      <% Link.last(3).reverse.each do |link| %>
        <%= render "links/preview", link: link %>
      <% end %>
      <%= link_to "more >>", links_url %>
    </div>

    <div id="selected_topics">
      <h2>Topics</h2>
      <p>
        <% Tag.top_topics.each do |count, tag_name, tag_id| %>
          <%= link_to tag_name, tag_path(tag_id), target: "_top" %> (<%= count %>),
        <% end %>
        <%= link_to "more >>", tags_url %>
      </p>
    </div>

    <div id="source_types">
      <h2>Source types</h2>
      <p>
        <% Tag.top_source_types.each do |count, tag_name, tag_id| %>
          <%= source_type_icon(tag_name) %>
          <%= link_to tag_name.humanize, tag_path(tag_id), target: "_top" %> (<%= count %>),
        <% end %>
        <%= link_to "more >>", tags_url %>
      </p>
    </div>

    <div id="about">
      <h2>About</h2>
      <p>The links referenced on this site may not have been reviewed, and do not necessarily reflect the views of the site's owner. Please exercise critical reading/listening/watching skills when engaging with their content.</p>
      <p>This website is powered by <a href="https://github.com/rshipp/link_organizer">Link Organizer</a>, and human labor.</p>
    </div>

    <div id="contribute">
      <h2>Contribute</h2>
      <% if current_user %>
        <p><%= link_to "Add new links", import_links_path %></p>
      <% else %>
        <p><%= link_to "Create an account", users_sign_in_path %> to add new links. Your email will not be public, and will never be used except to send you sign-in codes when you request them.</p>
      <% end %>
      <% if current_user&.admin %>
        <p><%= link_to "Tag and summarize unprocessed links", unprocessed_links_path %></p>
        <p><%= link_to "Process queued links", queued_links_path %></p>
      <% end %>
      <p>There are currently <%= QueuedLink.active.count %> user-submitted links in the queue, awaiting approval.</p>
    </div>
  <% end %>
<% end %>

app/views/home/_search_results.html.erb
<%= turbo_frame_tag "search_results", target: "_top", refresh: "morph" do %>
  <turbo-stream action="update" target="page-title">
    <template><%= query + " | " + site_name %></template>
  </turbo-stream>
  <% if links.present? || tags.present? %>
    <div id="search_results">
      <% if links.present? %>
        <h2>Links</h2>
        <% links.each do |link| %>
          <%= render "links/preview", link: link %>
        <% end %>
      <% end %>

      <% if tags.present? %>
        <h2>Tags</h2>
        <% tags.each do |tag| %>
          <p><%= link_to tag.name, tag, target: "_top" %> (<%= tag.links.count %>)</p>
        <% end %>
      <% end %>
    </div>
  <% elsif query.present? %>
    <p>No results found</p>
    <p>
      Don't see what you're looking for?
      Try <%= link_to "processing some links", unprocessed_links_path %> yourself, to make sure they have the correct tags!
    </p>
  <% end %>
<% end %>

app/views/home/advanced_search.html.erb
<%= content_for :title, "Advanced Search" %>

<div class="container m-auto ">
  <h1 class="text-center">Search <%= Rails.application.config.site_topic %> Links</h1>

  <div id="search" class="m-0 w-full md:m-auto md:w-fit">
    <%= form_with url: advanced_search_results_path, method: 'GET', data: {turbo: false}, class: 'not-prose' do |form| %>
      <%= form.text_field :query, 
            value: @query,
            type: 'search',
            class: "sm:w-full md:w-[32rem]",
            autofocus: true,
            aria: { label: 'Search query' } %>

      <details>
        <summary>Search tips</summary>
        <ul class="mt-0">
          <li class="mt-0">Use quotes to search "an exact phrase".</li>
          <li>Use <strong>-word</strong> or <strong>NOT word</strong> to exclude a word.</li>
        </ul>
      </details>

      <fieldset class="mt-4">
        <legend>Search in:</legend>
        <%= form.collection_check_boxes :search_in, 
              ['title', 'notes', 'comment', 'text'],
              :to_s, :humanize do |b| %>
          <div>
            <% checked = b.text != 'text'.humanize %>
            <%= b.label(class: "inline-flex items-center") { b.check_box(checked: checked) + b.text } %>
          </div>
        <% end %>
      </fieldset>

      <div class="tag-combobox search-page-combobox mt-4">
        <%= form.combobox :and_tags,
              Tag.all.order(:name),
              label: 'With ALL of these tags',
              multiselect_chip_src: possibly_new_tag_chips_path,
              mobile_at: "640px" %>
      </div>

      <div class="tag-combobox mt-4">
        <%= form.combobox :or_tags,
              Tag.all.order(:name),
              label: 'With ANY of these tags',
              multiselect_chip_src: possibly_new_tag_chips_path,
              mobile_at: "640px" %>
      </div>

      <div class="tag-combobox mt-4">
        <%= form.combobox :not_tags,
              Tag.all.order(:name),
              label: 'With NONE of these tags',
              multiselect_chip_src: possibly_new_tag_chips_path,
              mobile_at: "640px" %>
      </div>

      <div class="mt-8">
        <%= form.submit "Search" %>
      </div>
    <% end %>

  </div>
</div>

app/views/home/advanced_search_results.html.erb
<%= content_for :title, "Advanced Search Results" %>

<div class="container m-auto ">
  <h1 class="text-center">Advanced Seach Results</h1>

  <div>
    <p>Search results for <strong><%= params[:query].present? ? params[:query] : 'anything' %></strong></p>
    <ul>
      <% if params[:query].present? %>
        <li>In: <%= params[:search_in].compact_blank.map(&:humanize).map(&:downcase).join(', ') %></li>
      <% end %>
      <% if @and_tags.present? %>
        <li>With ALL tags: <%= @and_tags.map(&:name).join(', ') %></li>
      <% end %>
      <% if @or_tags.present? %>
        <li>With ANY tags: <%= @or_tags.map(&:name).join(', ') %></li>
      <% end %>
      <% if @not_tags.present? %>
        <li>Without tags: <%= @not_tags.map(&:name).join(', ') %></li>
      <% end %>
    </ul>
  </div>

  <% if @links.present? %>
    <div id="search_results">
      <h2>Links</h2>
      <% @links.each do |link| %>
        <%= render "links/preview", link: link %>
      <% end %>
    </div>
  <% else %>
    <p>No results found</p>
    <p>
      Don't see what you're looking for?
      Try <%= link_to "processing some links", unprocessed_links_path %> yourself, to make sure they have the correct tags!
    </p>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container m-auto ">
  <h1 class="text-center">Search <%= site_name %></h1>

  <div id="search" class="m-0 w-full md:m-auto md:w-fit">
    <%= form_with url: root_path, method: 'GET',
          data: { controller: "search", turbo_frame: "dynamic_homepage", turbo_action: "advance" } do |form| %>
      <%= form.text_field :query, 
            value: @query,
            type: 'search',
            class: "sm:w-full md:w-[32rem]",
            autofocus: true,
            data: { action: "input->search#search" },
            aria: { label: 'Search query' } %>
    <% end %>
  </div>
  <div class="m-0 w-full md:m-auto md:w-fit">
    <p class="mt-2 text-center">
      Or try <%= link_to "advanced search", advanced_search_path %>
    </p>
  </div>

  <%= render "dynamic_homepage", links: @links, tags: @tags, query: @query %>
</div>