config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, controller: 'sessions'

  ### Admin users
  constraints Passwordless::Constraint.new(User, if: -> (user) { user.admin }) do
    resources :links, only: [:edit, :update, :destroy] do
      get :unprocessed, to: 'links#unprocessed', on: :collection
    end
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :queued_links, only: [:index, :show, :destroy] do
      post :apply, to: 'queued_links#apply', on: :member
    end
  end

  ### Logged-in users
  constraints Passwordless::Constraint.new(User) do
    resources :links, only: [:new, :create] do
      get :import, to: 'links#import_new', on: :collection
      post :import, to: 'links#import_create', on: :collection
      post :import, to: 'links#run_import', on: :member
    end
    # combobox
    post "possibly_new_tag_chips", to: "tag_chips#create_possibly_new"
  end

  ### Anonymous users
  resources :tags, only: [:index, :show]
  resources :links, only: [:index, :show]
  get :advanced_search, to: 'home#advanced_search'
  get :advanced_search_results, to: 'home#advanced_search_results'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/link.rb
class Link < ApplicationRecord
  has_and_belongs_to_many :tags

  def topics
    tags.where(category: 'topic')
  end

  def source_types
    tags.where(category: 'source_type')
  end

  def topic_ids
    topics.map {|t| t.id}
  end

  def source_type_ids
    source_types.map {|t| t.id}
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy run_import ]

  # GET /links or /links.json
  def index
    if current_user&.admin
      @links = Link.all
    else
      # Hide links with a low rating for non-admins.
      @links = Link.where('rating > ?', 3).or(Link.where(rating: nil))
    end
  end

  # GET /links/unprocessed
  def unprocessed
    @links = Link.where(processed: false)

    if params[:no_topics]
      @links = @links.filter { |l| l.topics.empty? }
    end

    if params[:no_source_types]
      @links = @links.filter { |l| l.source_types.empty? }
    end

    if params[:no_archive]
      @links = @links.filter { |l| !l.archive_url&.present? }
    end

    if params[:tag]
      @links = @links.filter { |l| l.source_types.include? Tag.find_by(name: params[:tag]) }
    end
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/import
  def import_new
  end

  # POST /links/import
  def import_create
    links = params.require(:links).split

    if current_user&.admin
      links.each do |link|
        Rails.logger.debug("Enqueuing job with url=#{link}")
        ImportLinkJob.perform_later(link)
      end

      respond_to do |format|
        format.html { redirect_to unprocessed_links_url, notice: "Link import started. It may take a few minutes for new links to appear." }
        format.json { render :show, status: :created, location: unprocessed_links_url }
      end
    elsif current_user
      links.each do |link|
        QueuedLink.create(url: link, user: current_user)
      end

      respond_to do |format|
        format.html { redirect_to root_url, notice: "Links added to queue. Thank you!" }
        format.json { render :show, status: :created, location: root_url }
      end
    end
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    if current_user&.admin
      @link = Link.new(link_params)

      respond_to do |format|
        if @link.save
          update_tags
          format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
          format.json { render :show, status: :created, location: @link }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    elsif current_user
      @queued_link = QueuedLink.new(
        url: link_params[:url],
        data: link_params.except(:url),
        user: current_user,
      )

      respond_to do |format|
        if @queued_link.save
          format.html { redirect_to root_path, notice: "Link added to queue. Thank you!" }
          format.json { render json: {}, status: :created }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @queued_link.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # POST /links/1
  def run_import
    Rails.logger.debug("Enqueuing job with url=#{@link.url}, overwrite=true")
    # Force overwrite
    ImportLinkJob.perform_later(@link.url, true)

    respond_to do |format|
      format.html { redirect_to link_url(@link), notice: "Link import started. It may take a few minutes to update." }
      format.json { render :show, status: :created, location: link_url(@link) }
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        update_tags
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def update_tags
      tags = []

      # First, topic tags
      link_tag_params[:topic_ids].split(',').each do |tag_id|
        if (Integer(tag_id) rescue false)
          if tag = Tag.find(tag_id)
            tags << tag
          else
            Rails.logger.error("Missing topic tag with id=#{tag_id}")
          end
        else
          Rails.logger.info("Creating new tag=#{tag_id}")
          new_tag = Tag.create(name: tag_id, category: 'topic')
          tags << new_tag
        end
      end

      # Then, source_type tags
      link_tag_params[:source_type_ids].compact_blank.each do |tag_id|
        if tag = Tag.find(tag_id)
          tags << tag
        else
          Rails.logger.error("Missing source_type tag with id=#{tag_id}")
        end
      end

      # Then save.
      @link.tags = tags
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:url, :source_url, :comment, :archive_url, :text, :published_at, :title, :notes, :rating, :processed)
    end

    def link_tag_params
      params.require(:link).permit(:topic_ids, source_type_ids: [])
    end
end

app/views/links/_form.html.erb
<div class="not-prose max-w-[64rem]">
  <%= form_with model: @link, class: "flex flex-col space-y-4" do |form| %>
    <% if link.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
          <% link.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="mt-6">
      <%= form.label :url, "URL" %>
      <%= form.text_field :url %>
    </div>

    <div>
      <%= form.label :source_url, "Source URL" %>
      <%= form.text_field :source_url, aria: { describedby: "source-url-desc" }%>
      <p id="source-url-desc" class="text-sm text-italic">Social media post, or other source where this link was found. Optional.</p>

    </div>

    <div>
      <%= form.label :comment, "Comment (from source)" %>
      <%= form.text_area :comment, rows: 5 %>
    </div>

    <div>
      <%= form.label :published_at %>
      <%= form.datetime_field :published_at %>
    </div>

    <div>
      <fieldset>
        <legend>Source type</legend>

        <%= form.collection_check_boxes :source_type_ids,
              Tag.where(category: 'source_type').order(:name),
              :id, :humanized_name do |b| %>
          <div>
            <%= b.label(class: "inline-flex items-center") { b.check_box + b.text } %>
          </div>
        <% end %>
      </fieldset>
    </div>

    <div class="tag-combobox">
      <%= form.combobox :topic_ids,
            Tag.where(category: 'topic').order(:name),
            label: 'Topics',
            multiselect_chip_src: possibly_new_tag_chips_path,
            name_when_new: 'link[topic_ids]',
            mobile_at: "640px" %>
    </div>

    <div>
      <%= form.label :notes %>
      <%= form.text_area :notes, rows: 10, aria: { describedby: "notes-desc" } %>
      <p id="notes-desc" class="text-sm text-italic">Summarize the article, and add any important details.</p>
    </div>

    <div data-controller="archive" data-archive-url-value="<%= @link.url %>">
      <%= form.label :archive_url, "Archive URL" %>
      <%= form.text_field :archive_url,
            aria: { describedby: "archive-url-desc" },
            data: { 'archive-target': 'input' } %>
      <p id="archive-url-desc" class="text-sm">
        Archived copy of this link on <%= link_to 'archive.is', "https://archive.is/submit/?url=#{@link.url}", target: "_blank" %>
        or <%= link_to 'web.archive.org', "https://web.archive.org/web/*/#{@link.url}", target: "_blank" %>.
      </p>
    </div>

    <div>
      <%= form.label :text %>
      <%= form.text_area :text, rows: 10, aria: { describedby: "text-desc" } %>
      <p id="text-desc" class="text-sm text-italic">The full text of the article, originally pulled automatically from the webpage. May be messy.</p>
    </div>

    <div>
      <fieldset class="">
        <legend>How useful does this seem as a reference or resource?</legend>
        <div>
          <%= form.radio_button :rating, 1 %>
          <%= form.label :rating_1, "Seems not very useful / seems like a bad source" %>
        </div>
        <div>
          <%= form.radio_button :rating, 10 %>
          <%= form.label :rating_9, "Might be very useful / seems like a great source" %>
        </div>
      </fieldset>
    </div>

    <div>
      <fieldset>
        <legend>Have you reviewed the link content, edited the tags, summarized in the Notes field, and made any other necessary changes?</legend>
        <%= form.check_box :processed %>
        <%= form.label :processed, "Yes, mark this link as Processed!" %>
      </fieldset>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <h1><%= link.title %></h1>

  <%= link_to link.url, link.url %>
  <% if link.archive_url.present? %>
    (<%= link_to 'archive', link.archive_url %>)
  <% end %>

  <% if link.source_url.present? %>
    <blockquote>
      <p>
        <%= link.comment %>
      </p>
    </blockquote>
    <figcaption>
      <p>
        Source: <%= link_to link.source_url, link.source_url %>
      </p>
    </figcaption>
  <% end %>

  <h2>Notes</h2>
  <p>
    <%= link.notes %>
  </p>


  <h2>Tags</h2>
  <p>
    <strong>Source types:</strong>
  </p>
  <ul>
    <% link.source_types.each do |tag| %>
      <li><%= link_to tag.name.humanize, tag %></li>
    <% end %>
  </ul>

  <p>
    <strong>Topics:</strong>
  </p>
  <ul>
    <% link.topics.order(:name).each do |tag| %>
      <li><%= link_to tag.name, tag %></li>
    <% end %>
  </ul>

  <% if current_user&.admin %>
    <h2>Text</h2>
    <details>
      <summary>Expand full text</summary>
      <pre class="whitespace-pre-wrap bg-white font-sans text-black text-base">
        <%= link.text %>
      </pre>
    </details>
  <% end %>
  <br>
</div>

app/views/links/_link_preview.html.erb
<p>
  <% link.source_types.each do |source_type| %>
    <% case source_type.name -%>
    <% when "academic_article" %>
      🎓
    <% when "book" %>
      📕
    <% when "news_article" %>
      📰
    <% when "podcast" %>
      🎧
    <% when "social_post" %>
      🗨
    <% when "video" %>
      🎥
    <% end %>
  <% end %>
  <%= link_to link.title, link, data: { turbo_scroll: 'reset' } %>
</p>
<% if link.notes.present? %>
  <p><%= link.notes %></p>
<% end %>

app/views/links/_preview.html.erb
<p>
  <small><%= url_domain(link.url) %></small>
  <br/>
  <% link.source_types.each do |source_type| %>
    <%= source_type_icon(source_type.name) %>
  <% end %>
  <%= link_to link, target: "_top" do %>
    <% link.source_types.each do |source_type| %>
      <span class="sr-only"><%= source_type.name&.humanize %></span>
    <% end %>
    <%= link.title.present? ? link.title : '[Missing title]' %>
  <% end %>
</p>
<% if link.notes.present? %>
  <p class="-mt-2"><%= link.notes %></p>
<% end %>

app/views/links/edit.html.erb
<%= content_for :title, "Edit Link: #{@link.title.present? ? @link.title : @link.url}" %>

<h1>Editing link</h1>

<% if @link.archive_url.present? %>
  <p>View: <%= link_to "Open archived copy in a new tab", @link.archive_url, target: "_blank" %> (or <%= link_to "open the original", @link.url, target: "_blank" %>)</p>
<% elsif @link.url.present? %>
  <p>View: <%= link_to "Open this link in a new tab", @link.url, target: "_blank" %></p>
<% end %>

<%= render "form", link: @link %>

<div>
  <%= form_with url: import_link_path(@link) do |form| %>
    <%= form.submit 'Run automatic import', class: 'btn-danger', data: { turbo_confirm: 'Are you sure? Existing information will be overwritten! This is destructive!' } %>
  <% end %>
</div>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "View all links", links_path %>
</div>

app/views/links/import_new.html.erb
<%= content_for :title, "Import Links" %>

<h1>Import links</h1>

<div class="not-prose max-w-full w-full">
  <%= form_with url: import_links_path, class: "flex flex-col space-y-4" do |form| %>
    <%= form.label :links, "Enter links, one per line" %>
    <%= form.text_area :links, rows: 10 %>

    <%= form.submit "Import" %>
  <% end %>
</div>

app/views/links/index.html.erb
<%= content_for :title, "Links" %>

<h1>Links</h1>

<div id="links">
  <% @links.order(:created_at).reverse.each do |link| %>
    <%= render "preview", link: link %>
  <% end %>
</div>

<% if current_user %>
  <%= link_to "Import new links", import_links_path %> |
  <%= link_to "Manually add new link", new_link_path %>
<% end %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<% if @link.title.present? %>
  <%= content_for :title, @link.title + " | #{url_domain(@link.url)}"%>
<% else %>
  <%= content_for :title, @link.url %>
<% end %>

<%= render @link %>

<div>
  <% if current_user&.admin %>
    <%= link_to "Edit this link", edit_link_path(@link) %> |
  <% end %>
  <%= link_to "View all links", links_path %>
</div>

<% if current_user&.admin %>
  <div>
    <br/>
    <%= button_to "Destroy this link", @link, method: :delete, class: 'btn-danger', form: { data: { turbo_confirm: 'Are you sure?' } } %>
  </div>
<% end %>

app/views/links/unprocessed.html.erb
<%= content_for :title, "Unprocessed Links" %>

<h1>Unprocessed Links</h1>

<div class="text-black text-lg max-w-[64rem] ">
  <p>
    Manually summarizing and adding relevant tags to links makes it easier to find the one you're looking for in the future.
  </p>
  <p>
    The links below have not yet been processed by a person, and may have incorrect tags, missing summary, and other incorrect information.
    Please review the link content, edit its tags, and write a quick summary or any important details in the "Notes" field.
    When you've fully filled in the tags and notes, and edited any other fields that need changing, check the "Processed" box, and save the link details with the "Update Link" button.
  </p>
  <p>
    By default, this page shows "Unprocessed" links. You may also want to limit to links with
    <%= link_to 'no topics', unprocessed_links_path(no_topics: true) %>,
    <%= link_to 'no source types', unprocessed_links_path(no_source_types: true) %>,
    or
    <%= link_to 'no archived copy', unprocessed_links_path(no_archive: true) %>.
  </p>
  <p>
    There are <%= @links.count %> unprocessed links remaining
    <% if params[:no_topics] || params[:no_source_types] || params[:no_archive] || params[:tag] %>
      with
      <%= [
        params[:no_topics] && 'no topics',
        params[:no_source_types] && 'no source types',
        params[:no_archive] && 'no archived copy',
        params[:tag] && "the tag '#{params[:tag]}'",
      ].compact_blank.join(' and ') %>
    <% end %>
    (out of <%= Link.count %> total).
  </p>
</div>

<h2>Unprocessed Links</h2>
<div id="links">
  <% @links.each do |link| %>
    <p>
      <%= link_to link.title, edit_link_path(link) %>
    </p>
  <% end %>
</div>