config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, controller: 'sessions'

  ### Admin users
  constraints Passwordless::Constraint.new(User, if: -> (user) { user.admin }) do
    resources :links, only: [:edit, :update, :destroy] do
      get :unprocessed, to: 'links#unprocessed', on: :collection
    end
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :queued_links, only: [:index, :show, :destroy] do
      post :apply, to: 'queued_links#apply', on: :member
    end
  end

  ### Logged-in users
  constraints Passwordless::Constraint.new(User) do
    resources :links, only: [:new, :create] do
      get :import, to: 'links#import_new', on: :collection
      post :import, to: 'links#import_create', on: :collection
      post :import, to: 'links#run_import', on: :member
    end
    # combobox
    post "possibly_new_tag_chips", to: "tag_chips#create_possibly_new"
  end

  ### Anonymous users
  resources :tags, only: [:index, :show]
  resources :links, only: [:index, :show]
  get :advanced_search, to: 'home#advanced_search'
  get :advanced_search_results, to: 'home#advanced_search_results'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/queued_link.rb
class QueuedLink < ApplicationRecord
  belongs_to :user

  validates_presence_of :url

  scope :active, -> { where(deleted_at: nil, applied_at: nil) }
end

app/controllers/queued_links_controller.rb
class QueuedLinksController < ApplicationController
  before_action :set_queued_link, only: %i[ show apply destroy ]

  def index
    @queued_links = QueuedLink.active
  end

  def show
  end

  def apply
    if @queued_link.data.present?
      Link.create!(
          url: @queued_link.url,
          **@queued_link.data
      )
    else
      ImportLinkJob.perform_later(@queued_link.url)
    end
    @queued_link.update!(applied_at: DateTime.now)

    respond_to do |format|
      format.html { redirect_to unprocessed_links_url, notice: "Link import started. It may take a few minutes for new links to appear." }
      format.json { render :show, status: :created, location: unprocessed_links_url }
    end
  end

  def destroy
    @queued_link.update!(deleted_at: DateTime.now)

    respond_to do |format|
      format.html { redirect_to queued_links_url, notice: "Link was successfully removed from queue." }
      format.json { head :no_content }
    end
  end

  private
    def set_queued_link
      @queued_link = QueuedLink.find(params[:id])
    end
end

app/views/queued_links/index.html.erb
<%= content_for :title, "Queue" %>

<h1>Queue</h1>

<div id="queue">
  <% @queued_links.order(:created_at).reverse.each do |link| %>
    <p><%= link_to link.url, link %></p>
  <% end %>
</div>

app/views/queued_links/show.html.erb
<h1>Queued link #<%= @queued_link.id %></h1>

<p>
  URL: 
  <% link = Link.find_by(url: @queued_link.url) %>
  <% if link.present? %>
    (<%= link_to 'already exists', link %>) -
  <% end %>
  <%= link_to @queued_link.url, @queued_link.url %>
</p>
<p>User: <%= @queued_link.user.email %></p>
<% if @queued_link.data.present? %>
  <% @queued_link.data.each do |key, value| %>
    <p><%= key.humanize %>: <%= value %></p>
  <% end %>
<% end %>

<br />
<%= form_with url: apply_queued_link_path, method: :post do |form| %>
  <%= form.submit 'Import link', class: 'btn-danger', data: { turbo_confirm: 'Are you sure? This link will be imported.' } %>
<% end %>
<%= button_to 'Delete link from queue', @queued_link, method: :delete, class: 'btn-danger', form: { data: { turbo_confirm: 'Are you sure? This link will be removed from the queue.' } } %>