config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, controller: 'sessions'

  ### Admin users
  constraints Passwordless::Constraint.new(User, if: -> (user) { user.admin }) do
    resources :links, only: [:edit, :update, :destroy] do
      get :unprocessed, to: 'links#unprocessed', on: :collection
    end
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :queued_links, only: [:index, :show, :destroy] do
      post :apply, to: 'queued_links#apply', on: :member
    end
  end

  ### Logged-in users
  constraints Passwordless::Constraint.new(User) do
    resources :links, only: [:new, :create] do
      get :import, to: 'links#import_new', on: :collection
      post :import, to: 'links#import_create', on: :collection
      post :import, to: 'links#run_import', on: :member
    end
    # combobox
    post "possibly_new_tag_chips", to: "tag_chips#create_possibly_new"
  end

  ### Anonymous users
  resources :tags, only: [:index, :show]
  resources :links, only: [:index, :show]
  get :advanced_search, to: 'home#advanced_search'
  get :advanced_search_results, to: 'home#advanced_search_results'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :links

  def humanized_name
    name.humanize
  end

  def to_s
    # called by combobox for some godawful reason
    to_combobox_display
  end

  def to_combobox_display
    name
  end

  # Class methods
  def self.top_topics
    Tag.top_tags(:topic, 10)
  end

  def self.top_source_types
    Tag.top_tags(:source_type, 7)
  end

  def self.top_tags(category, count)
    # Returns [[count, tag_name, tag_id]]
    Link.joins(:tags)
      .where(tags: {category: category})
      .group(:name, 'tags.id')
      .count.sort_by { |k, v| v }
      .last(count)
      .reverse
      .map do |tag_info, count|
        [count, tag_info[0], tag_info[1]]
      end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name, :category, :description)
    end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category %>
    <%= form.select :category, ['topic', 'source_type'] %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= tag.category %>
  </p>

</div>

app/views/tags/edit.html.erb
<%= content_for :title, "Edit Tag: #{@tag.name}" %>

<h1>Editing tag: <%= @tag.name %></h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<%= content_for :title, "Tags" %>

<h1>Tags</h1>

<h2>Source types</h2>

<div id="source_types">
  <% @tags.where(category: 'source_type').order(:name).each do |tag| %>
    <p>
      <%= source_type_icon(tag.name) %>
      <%= link_to tag.name, tag %> (<%= tag.links.count %>)
    </p>
  <% end %>
</div>

<h2>Topics</h2>

<div id="topics">
  <% @tags.where(category: 'topic').order(:name).each do |tag| %>
    <p>
      <%= link_to tag.name, tag %> (<%= tag.links.count %>)
    </p>
  <% end %>
</div>

<% if current_user&.admin %>
  <div>
    <p>
      Don't see what you're looking for?
      Try <%= link_to "processing some links", unprocessed_links_path %> yourself, to make sure they have the correct tags!
    </p>
  </div>
<% end %>

app/views/tags/show.html.erb
<%= content_for :title, @tag.name.humanize %>

<h1><%= @tag.category&.humanize %>: <%= @tag.name&.humanize %></h1>

<div><%= markdown(@tag.description || '') %></div>

<h2>Links</h2>
<% @tag.links.each do |link| %>
  <%= render "links/preview", link: link %>
<% end %>

<% if current_user&.admin %>
  <div>
    <br/>
    <p>
      Don't see what you're looking for?
      Try <%= link_to "processing some links", unprocessed_links_path %> yourself, to make sure they have the correct tags!
    </p>
  </div>

  <div>
    <br/>
    <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
    <%= link_to "View all tags", tags_path %>
  </div>
  <div>
    <br/>
    <%= button_to "Destroy this tag", @tag, method: :delete, class: "btn-danger", form: { data: { turbo_confirm: 'Are you sure?' } } %>
  </div>
<% else %>
  <div>
    <br/>
    <%= link_to "View all tags", tags_path %>
  </div>
<% end %>